services:
  postgres:
    container_name: invtrackdb
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres: